# Generated by Django 3.2.8 on 2022-01-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
