# Generated by Django 3.2.8 on 2022-03-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='each_id',
        ),
    ]
