# Generated by Django 3.2.8 on 2022-03-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_id_category_each_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='each_id',
            new_name='id',
        ),
    ]
