# Generated by Django 4.0.3 on 2022-04-14 03:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_category_each_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
