# Generated by Django 4.0.3 on 2022-04-14 04:49

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_laptops_slug_laptops_star_phone_star_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptops',
            options={'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': 'Popular Products'},
        ),
        migrations.AlterModelOptions(
            name='popularproducts',
            options={'verbose_name_plural': 'Popular Products'},
        ),
        migrations.AlterModelOptions(
            name='television',
            options={'verbose_name_plural': 'Televisions'},
        ),
        migrations.AddField(
            model_name='popularproducts',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='popularproducts',
            name='star',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='television',
            name='star',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='star',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='popularproducts',
            name='price',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='television',
            name='price',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='television',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
