# Generated by Django 4.0.3 on 2022-04-14 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_laptops_options_alter_phone_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
