# Generated by Django 4.0.3 on 2022-04-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name_plural': 'Phones'},
        ),
    ]
