# Generated by Django 4.0.3 on 2022-04-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_laptops_slug_alter_phone_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='popularproducts',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='television',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
